'use client';

import { defineCatalog } from '@json-render/core';
import { schema } from '@json-render/react/schema';
import {
  defineRegistry,
  Renderer,
  StateProvider,
  VisibilityProvider,
  ActionProvider,
  type Spec,
} from '@json-render/react';
import { catalogDefs } from './catalog-defs.js';

export { catalogDefs } from './catalog-defs.js';
export type { CatalogComponent } from '../util/catalog.js';

/** Catalog component metadata (name → Zod props + description + slots), keyed for defineCatalog. */
export const components = Object.fromEntries(
  catalogDefs.map((d) => [
    d.name,
    { props: d.props, slots: d.slots ?? [], description: d.description },
  ]),
);

/** The json-render catalog — the machine-readable declaration of what this design system offers. */
export const catalog = defineCatalog(schema, { components, actions: {} });

/** Binds each catalog component name to its React renderer, so a json-render spec renders as this DS. */
export const { registry } = defineRegistry(catalog, {
  components: Object.fromEntries(catalogDefs.map((d) => [d.name, d.render])),
});

/** A json-render spec in this design system's flat `{ root, elements, state? }` form. */
export type PreviewSpec = Spec;

/**
 * Render a json-render spec through this design system, with the full provider stack the renderer
 * needs (state, visibility, actions). Drop `<SpecView spec={…} />` anywhere — e.g. to render a spec
 * generated by Lighter.
 */
export function SpecView({ spec }: { spec: PreviewSpec }) {
  return (
    <StateProvider>
      <VisibilityProvider>
        <ActionProvider handlers={{}}>
          <Renderer spec={spec} registry={registry} />
        </ActionProvider>
      </VisibilityProvider>
    </StateProvider>
  );
}
