'use client';

import { defineCatalog } from '@json-render/core';
import { schema } from '@json-render/react/schema';
import {
  defineRegistry,
  Renderer,
  StateProvider,
  VisibilityProvider,
  ActionProvider,
  type Spec,
} from '@json-render/react';
import { catalogDefs } from './catalog-defs.js';
import { annotatedRegistry, AnnotationRoot } from './annotate.js';

export { catalogDefs } from './catalog-defs.js';
export { ELEMENT_ID_ATTR } from './annotate.js';
export type { CatalogComponent } from '../util/catalog.js';

/** Catalog component metadata (name → Zod props + description + slots), keyed for defineCatalog. */
export const components = Object.fromEntries(
  catalogDefs.map((d) => [
    d.name,
    { props: d.props, slots: d.slots ?? [], description: d.description },
  ]),
);

/** The json-render catalog — the machine-readable declaration of what this design system offers. */
export const catalog = defineCatalog(schema, { components, actions: {} });

/** Binds each catalog component name to its React renderer, so a json-render spec renders as this DS. */
export const { registry } = defineRegistry(catalog, {
  components: Object.fromEntries(catalogDefs.map((d) => [d.name, d.render])),
});

/** A json-render spec in this design system's flat `{ root, elements, state? }` form. */
export type PreviewSpec = Spec;

/**
 * Render a json-render spec through this design system, with the full provider stack the renderer
 * needs (state, visibility, actions). Drop `<SpecView spec={…} />` anywhere — e.g. to render a spec
 * generated by Lighter.
 *
 * `annotate` opts into review tooling (#160): each element is tagged with its spec id on a
 * `display: contents` wrapper, so Lighter's review surface can hit-test elements and anchor comments.
 * It generates no box, and it is **off by default** — a consumer app renders exactly the DOM it always
 * did, which is what keeps the review surface and the product visually identical (#158).
 */
export function SpecView({ spec, annotate = false }: { spec: PreviewSpec; annotate?: boolean }) {
  const tree = (
    <StateProvider>
      <VisibilityProvider>
        <ActionProvider handlers={{}}>
          <Renderer
            spec={spec}
            registry={(annotate ? annotatedRegistry : registry) as typeof registry}
          />
        </ActionProvider>
      </VisibilityProvider>
    </StateProvider>
  );
  return annotate ? <AnnotationRoot rootId={spec.root}>{tree}</AnnotationRoot> : tree;
}
