import type { Hono } from 'hono';
import { toJsonRender, type Spec } from '@lighter/spec';
import { catalogPrompt } from '@lighter/generation';
import { latestInventory, getVersionState, type Db } from '@lighter/db';
import type { InventoryModel } from '@lighter/ingestion';
import type { SpecStore } from './specStore.js';

/**
 * A standalone React export of the spec (#33): a self-contained `.tsx` that embeds the json-render
 * spec and renders it through the design system's `<SpecView>`. json-render has no source codegen, so
 * this is the runnable, dependency-light React artifact for the handoff — drop it into a project that
 * has the design system and it renders the approved screen.
 */
export function toReactExport(spec: Spec, componentName = 'Screen'): string {
  const jr = toJsonRender(spec);
  return `import { SpecView, type PreviewSpec } from 'lighter-example/ui';

// Auto-generated by Lighter — the approved design as a json-render spec, rendered by the design system.
const spec = ${JSON.stringify(jr, null, 2)} as PreviewSpec;

export default function ${componentName}() {
  return <SpecView spec={spec} />;
}
`;
}

/**
 * Mount the handoff-bundle export (#33). A bundle is exported per approved screen version and contains
 * everything an engineer needs to build it: the approved spec, the catalog prompt (#31), the tokens
 * file, the screen's INTENT.md (#32), and a standalone React export. Export is allowed ONLY for a
 * version whose approval state is `approved` (#25) — an unapproved version is refused.
 */
export function registerHandoffRoutes(app: Hono, db: Db, store: SpecStore): void {
  app.get('/screens/:id/versions/:version/export', async (c) => {
    const id = c.req.param('id');
    const version = Number(c.req.param('version'));
    if (!Number.isInteger(version) || version < 1) {
      return c.json({ status: 'error', message: 'version must be a positive integer' }, 400);
    }
    const screen = await store.getScreen(id);
    const spec = await store.getVersion(id, version);
    if (!screen || !spec) {
      return c.json({ status: 'error', message: 'version not found' }, 404);
    }

    // Only an approved version may be exported.
    const state = (await getVersionState(db, id, version)) ?? 'draft';
    if (state !== 'approved') {
      return c.json(
        { status: 'error', message: 'only an approved version can be exported', state },
        403,
      );
    }

    // The catalog prompt + tokens come from the current ingested design system.
    const model = (await latestInventory(db)) as InventoryModel | null;
    if (!model) {
      return c.json({ status: 'error', message: 'no design-system catalog ingested' }, 422);
    }
    const catalog = model.components.map((comp) => ({
      name: comp.name,
      description: comp.description,
      props: comp.props,
    }));

    return c.json({
      screen,
      version,
      spec,
      catalogPrompt: catalogPrompt(catalog),
      tokens: model.tokens,
      intent: (await store.getIntent(id)) ?? '',
      reactExport: toReactExport(spec),
    });
  });
}
